version: "3.7"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - university
    volumes:
      - mongo:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - university
    # volumes: 
    #   - rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - university
    volumes: 
      - redis:/data

networks:
  university:
    name: university-network

volumes:
  mongo:
    driver: local
    
  redis:
    driver: local